trigger:
  branches:
    include:
    - master

variables:
  image_name: 'okampfer/pgweb'
  pgweb_version: '0.11.4'

jobs:
  - job: build_docker_image
    pool:
      vmImage: 'ubuntu-18.04'
    steps:
    - task: Docker@2
      displayName: Build and push
      inputs:
        command: buildAndPush
        containerRegistry: docker_hub_service_connection_okampfer
        repository: $(image_name)
        tags: |
          'latest'
          $(pgweb_version)
